library:
  source-dirs: src
tests:
  advent-of-code-v2019-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-v2019
copyright: 2019 Jakub Kozłowski
maintainer: kubukoz@gmail.com
dependencies:
- hspec
- mtl
- base >= 4.7 && < 5
name: advent-of-code-v2019
version: 0.1.0.0
author: Jakub Kozłowski
github: kubukoz/advent-of-code-v2019
license: MIT
executables:
  advent-of-code-v2019-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-v2019
description: Please see the README on GitHub at <https://github.com/githubuser/advent-of-code-v2019#readme>
